#!/bin/env python
import os.path


PATH = os.path.dirname(os.path.abspath(__file__))

files = [
    "cocuh-core.sty",
    "cocuh-math.sty",
    "cocuh-todo.sty",
    "cocuh-dummytext.sty",
    "notation.sty",
    "main.tex",
    "main.bib",
    "Makefile",
    ".latexmkrc",
    ".gitignore",
]

print('\n'.join(
    os.path.join(PATH, name)
    for name in files
))
